alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias ..... 'cd ../../../..'
alias 000 'chmod -R 000'
alias 644 'chmod -R 644'
alias 666 'chmod -R 666'
alias 755 'chmod -R 755'
alias 777 'chmod -R 777'
alias chmax 'chmod a+x'
alias ls 'colorls --sd --dark'
alias mkbz2 'tar -cvjf'
alias mkgz 'tar -cvzf'
alias mktar 'tar -cvf'
alias neofetch 'neofetch --ascii_distro Arch_small'
alias unbz2 'tar -xvjf'
alias ungz 'tar -xvzf'
alias untar 'tar -xvf'
